- addons.markdown
Add location and description to additional module providing date/time helpers.
> Add module definision date/time

- _layouts/bootstrap.html
- css/codeception.css
There was some troubles with menu on mobile devices.
And reformat code in _layouts/bootstrap.html
> Fix menu for mobile devices.

- addons.markdown
The module is on its first stages but we are already using it here https://github.com/joomla-extensions/weblinks/blob/master/tests/acceptance.suite.dist.yml#L17
> Add Joomla Browser Codeception Module

- index.markdown
Let us not confuse Tolkien, the master, with Jackson, the charlatan.
> Corrects the author of "The Hobbit"

- _posts/2013-11-12-working-with-phpunit-and-selenium-webdriver.md
Additional information in [this pull request](https://github.com/DavertMik/php-webdriver-demo/pull/1)
> Replaced close() to quit() in tearDown()

- addons.markdown
related to http://phptest.club/t/how-to-create-a-codeception-extension-to-check-your-tests-performance/374
> Add TestStatistics Extension

- quickstart.html
Updating documentation to use configs like the codeception bootstrap. Previous configs here did not work.
> Updating documentation to use configs like the codeception bootstrap

- addons.markdown
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/codeception/codeception.github.com/71)
> Add Teamcity plugin

- install.html
- quickstart.html
- thanks_php54.html
Related to https://github.com/Codeception/Codeception/pull/2752
> Added instructions how to download phar file for PHP 5.4

- css/codeception.css
+ fix long strings breaking out of the containers, especially in responsive views.
+ tweak lists to use available space in _xs, sm_ responsive views
> CSS tweaks: word-break, responsive lists

- _layouts/bootstrap.html
- _layouts/index.html
- css/codeception.css
+ fixed un-contained main navbar
+ touch-up calls to action
+ fixed floating twitter ’follow’
+ twitter ‘follow’ positioned as call to action
+ improved spacing of Examples
+ improved spaces of questions
+ editing of English
+ re-positioned badges
+ changes to css as appropriate
> Home page improvements.

- quickstart.html
5.3 as requirement at the top of quick start page can be misleading, so I changed it to 5.4.
> Bumped up required version of PHP

- addons.markdown
add link to https://github.com/oprudkyi/codeception-events-scripting
> Add EventsScripting extension

- addons.markdown
Codeception extension for supporting Fixtures in Gherkin scenario (parametrisable steps).
Example:
```feature
Scenario: Scenario using simple parameter
Given I have a parameter "test" with value "42"
Then I should see "{{test}}" equals "42"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codeception/codeception.github.com/91)
> Update addons.markdown - add GherkinParam

- for/wordpress.md
Here is a first draft for the "For WordPress" page.
> added WordPress doc first draft

- addons.markdown
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codeception/codeception.github.com/109)
> Update addons.markdown - add SecureShell

- for/yii.md
> Fixed typo in command name [skip ci]

- _posts/2013-11-12-working-with-phpunit-and-selenium-webdriver.md
> Fixed AcceptanceTests link in the old blog post

- for/yii.md
Just some words which missed a letter in this file 😄
> Some small typos in documentation fixed

- addons.markdown
> Added phiremock extension and module to addons page.

- addons.markdown
I forked the original CSS Regression repo and made some bugfixes, cleanups and updates to use the current Codeception module Api.
> Updated CSS Regression repo.

- addons.markdown
Thank you for posting about the module! Really appreciate that!
Hope the module will be useful to someone!
> Add a section about markup validator module

- for/symfony.md
Please add more, if I missed something!
> Mentioning core features on top of the page

- for/wordpress.md
Updates to the guide following release of wp-browser 1.21
> Update the guide per latest release

- _data/modules.yml
> adding appium driver module

- for/wordpress.md
Reported in: https://github.com/lucatume/wp-browser/issues/111
> correct the name of the default suite

- _data/modules.yml
More info https://github.com/hyperia-sk/codecept-unittest-generator
> New extension: Generate PHPUnit tests from annotations

- for/symfony.md
The API test suite configuration in the documentation is incorrect.
https://github.com/Codeception/Codeception/issues/4844
> [For Symfony] Correct the API test suite configuration

- for/symfony.md
...since this is already included in `composer require codeception/codeception --dev`
> Deleting "Project setup"

- for/symfony.md
Just a quick shot (i.e. no layout) to make editing easier. Should be included in the other "for" pages too.
> Added "edit this page" link

- docs/07-BDD.md
Fix for some awkward wording and grammar mistakes in the documentation for BBD.
> Documentation grammar fix

- _includes/phar.html
- install.html
Fixes https://github.com/Codeception/Codeception/issues/5600
> Set minimum required version of PHP to 5.6 

- _data/modules.yml
This module provides actions to test code which depends on PSR3 compatible logger.
> Add PSR3 Logger community modules

- _data/extensions.yml
Simple extension, that can be very useful and time-saving
> Add PauseOnFail extension

- for/wordpress.md
Mostly because I had to do this to get things working :)
> Added a section on Setting Environment variables

- RoboFile.php
- package/stub.php
Depends on https://github.com/Codeception/Codeception/pull/5751
> Phar file requires codeception/codeception/app.php

- _data/modules.yml
Hello the team,
Last day of the year, and with this pull request I finished one more goal for myself:
https://twitter.com/MailCare_io/status/1079711663396392961
I also followed the **Boy Scout Rule**:
- Sort A-Z
- Added period at the end of the description
- Always the same order: image, link, description, color
- Removed module in the name 
- Added my new module MailCare module 🥳
Thanks for your work this year on Codeception. Your modules inspired me to build the mailcare module.
> Add MailCare Module

- RoboFile.php
- changelog.markdown
> [Changelog] Add blank line between changelog files

- docs/06-ModulesAndHelpers.md
changed module to modules, improved formatting
> [Docs] Improved examples in ModulesAndHelpers

- install.html
> remove unnecessary tag

- css/codeception.css
- video.html
> add responsive video

- video.html
> remove frameborder in iframe

- _layouts/post.html
- css/codeception.css
> fix release post

- css/codeception.css
> fix indent in well block

- quickstart.html
> fix indents quickstart

- _layouts/post.html
> release post fix w3 validation

- _includes/comment.html
> fix w3 validation for disqus js

- _layouts/doc.html
> fix w3 validation for docs js

- docs/reference/Configuration.md
Changed from:
`coverage`: pre suite
To:
`coverage`: per suite
> Tiny typo change

- docs/07-BDD.md
> (docs) fix typo

- css/codeception.css
> fix footer icons on IE browser

- css/codeception.css
- quickstart.html
> fix collapse panel

- quickstart.html
> add responsive class to images

- css/codeception.css
> dropdown jumping fix

- css/codeception.css
> fix horizontal scroll on open dropdown

- _layouts/bootstrap.html
> add browserconfig

- video.html
> remove video

- docs/09-Data.md
Readme update for https://github.com/Codeception/Codeception/pull/5930
> Update snapshot readme

- _data/extensions.yml
- _data/modules.yml
Moving GherkinParam from extensions to module, since GherkinParam is now a Codeception module.
> Moved GherkinParam to modules

- _includes/yii_hero.html
- css/codeception.css
> change yii logo to svg on use cases page

- _includes/wp_hero.html
> update wordpress logo to svg

- _includes/joomla_hero.html
- css/codeception.css
> change logo to svg (joomla)

- quickstart.html
> add alt description to quickstart page

- _includes/phar.html
- css/codeception.css
> update collapse block on phar page

- css/codeception.css
- quickstart.html
> update head panel on mobile

- css/codeception.css
> fix docs dropdown

- _layouts/bootstrap.html
issue https://github.com/Codeception/codeception.github.com/issues/302
> update google font

- _includes/js.html
- _layouts/bootstrap.html
issue https://github.com/Codeception/codeception.github.com/issues/304
> replace js include

- _layouts/bootstrap.html
- _layouts/doc.html
- _layouts/page.html
- index.html
issue https://github.com/Codeception/codeception.github.com/issues/308
> fixes site js

- _layouts/bootstrap.html
- css/style.css
https://github.com/Codeception/codeception.github.com/issues/316
> refactor css

- 404.html
https://github.com/Codeception/codeception.github.com/issues/321
> remove the extra character

- _layouts/bootstrap.html
https://github.com/Codeception/codeception.github.com/issues/328
> update head styles

- _includes/algolia.html
https://github.com/Codeception/codeception.github.com/issues/340
> update algolia js

- docs/07-AdvancedUsage.md
- docs/12-ParallelExecution.md
- for/laravel.md
- for/symfony.md
- for/yii.md
Removing PhantomJS, see https://github.com/Codeception/module-webdriver/issues/28#issuecomment-720139366
> Remove PhantomJS from ParallelExecution and framework pages

- _layouts/bootstrap.html
https://github.com/Codeception/codeception.github.com/issues/382
> remove unused class

- docs/03-AcceptanceTests.md
of https://github.com/Codeception/codeception.github.com/pull/367 this time :-)
> Second attempt part 2

- for/laravel.md
> Replace Laravel5 module with Laravel module

- docs/01-Introduction.md
See https://github.com/Codeception/Codeception/discussions/6063#discussioncomment-245077
Question: How can I get the yellow `<div class="alert alert-warning">`?
> Adding "edit" link

- docs/01-Introduction.md
Follow up of https://github.com/Codeception/codeception.github.com/pull/410
Is the empty `<p>` really the best way to get some margin?
> Fixing "edit" link

- docs/01-Introduction.md
After https://github.com/Codeception/codeception.github.com/pull/415
> Fixing "edit" link again ;-)

- docs/11-Codecoverage.md
Fix issue https://github.com/Codeception/Codeception/issues/5099
> Update 11-Codecoverage.md for dev domain

- docs/03-AcceptanceTests.md
- docs/04-FunctionalTests.md
- docs/05-UnitTests.md
- docs/reference/Configuration.md
As per [this comment](https://github.com/Codeception/codeception.github.com/pull/431#issuecomment-761783912), I have created PR to fix #440
> Add missing error_level parameter

- docs/modules/Symfony.md
> Updated Symfony module docs

- Gemfile
https://github.com/Codeception/codeception.github.com/issues/549
> upd algolia plugin

- _data/extensions.yml
- _data/modules.yml
https://github.com/Codeception/codeception.github.com/issues/551
> update data links

- _includes/companies.html
https://github.com/Codeception/codeception.github.com/issues/553
> update companies links

- _layouts/bootstrap.html
- _layouts/doc.html
- _layouts/page.html
- _layouts/post.html
https://github.com/Codeception/codeception.github.com/issues/558
> update layout links

- _layouts/doc.html
https://github.com/Codeception/codeception.github.com/issues/564
> fix docs on tablet

- _scss/_algolia.scss
https://github.com/Codeception/codeception.github.com/issues/566
> update btn group on mobile

- RoboFile.php
See https://github.com/Codeception/module-symfony/issues/125#issuecomment-804688770
> Removing version links from modules' docs pages

- docs/06-ModulesAndHelpers.md
See https://github.com/Codeception/Codeception/issues/5741#issuecomment-753626197
TODO: Add a link from https://codeception.com/docs/02-GettingStarted#Interactive-Pause to here after this was merged.
> Explaining `Pause` trait

- _layouts/bootstrap.html
- _scss/_main.scss
https://github.com/Codeception/codeception.github.com/issues/571
> update navbar toggle btn

- _scss/_algolia.scss
- _scss/_highlight.scss
- _scss/_main.scss
- _scss/_support.scss
https://github.com/Codeception/codeception.github.com/issues/576
> refactor scss

- video.html
https://github.com/Codeception/codeception.github.com/issues/579
> Accessibility - update iframes

- for/yii.md
https://github.com/Codeception/codeception.github.com/issues/605
> update yii.md links

- builds.markdown
https://github.com/Codeception/codeception.github.com/issues/621
> update builds.md links

- docs/08-Customization.md
Documents https://github.com/Codeception/Codeception/pull/6435
> Document suite wildcards for multi application setup

- docs/07-AdvancedUsage.md
- for/laravel.md
- for/phalcon.md
see https://github.com/Codeception/Codeception/pull/6520
> Not powered by PHPUnit

- _posts/2022-07-02-codeception-5.markdown
- docs/12-ParallelExecution.md
- docs/ParallelExecution.md
- guides/12-ParallelExecution.md
Hello. Thank you for your work! I have been noticed that there is a typo in documentation, so i tried to fix this.
> fix typo (venodor -> vendor)

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/657
> Accessibility upd color contrast

- guides/06-ModulesAndHelpers.md
Signed-off-by: imme-emosol <will+developer@willfris.nl>
> Minor corrections in Modules And Helpers

- docs/02-GettingStarted.md
- docs/03-AcceptanceTests.md
- docs/06-ModulesAndHelpers.md
- docs/07-AdvancedUsage.md
- docs/AcceptanceTests.md
- docs/AdvancedUsage.md
- docs/GettingStarted.md
- docs/ModulesAndHelpers.md
- quickstart.html
Codeception 5 does not generate per-suite helpers anymore
> Remove outdated helper information

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/667
> Accessibility update color contrast text

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/669
> Accessibility update color contrast alert warning

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/671
> update color contrast

- Gemfile
resolve https://github.com/Codeception/codeception.github.com/issues/676
> update Gemfile for windows

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/680
> update go top btn

- docs/modules/Db.md
- docs/modules/Doctrine2.md
- docs/modules/FTP.md
- docs/modules/Memcache.md
- docs/modules/Phalcon.md
- docs/modules/Phalcon4.md
- docs/modules/Yii2.md
resolve https://github.com/Codeception/codeception.github.com/issues/685
> update docs links

- _includes/sponsors.html
resolve https://github.com/Codeception/codeception.github.com/issues/693
> remove backer

- _includes/phar.html
resolve https://github.com/Codeception/codeception.github.com/issues/695
> Accessibility fix accordion

- _includes/phar.html
resolve https://github.com/Codeception/codeception.github.com/issues/697
> fix accordion

- _includes/phar.html
- thanks.html
- thanks_php5.html
- thanks_php80.html
I expect to see new accordion section in https://codeception.com/install page.
> Add Codeception 5 phar file to installation page

- _includes/phar.html
resolve https://github.com/Codeception/codeception.github.com/issues/708
> remove unnecessary styles

- _scss/_main.scss
resolve https://github.com/Codeception/codeception.github.com/issues/718
> update top arrow on mobile

- index.html
resolve https://github.com/Codeception/codeception.github.com/issues/810
> min svg index.html

- _layouts/bootstrap.html
resolve https://github.com/Codeception/codeception.github.com/issues/812
> Accessibility update nav

- _layouts/bootstrap.html
resolve https://github.com/Codeception/codeception.github.com/issues/816
> update License link

- _includes/phar.html
resolve https://github.com/Codeception/codeception.github.com/issues/818
> Accessibility update toggle

- quickstart.html
resolve https://github.com/Codeception/codeception.github.com/issues/822
> Accessibility update

- quickstart.html
resolve https://github.com/Codeception/codeception.github.com/issues/824
> Accessibility toggle

- docs/UnitTests.md
Elaborate on recommendation for API to use with Stub/Mock creation.
> Expand Stub-API recommendation in UnitTests.md [close #826]

- _includes/sponsors.html
resolve https://github.com/Codeception/codeception.github.com/issues/834
> remove supporter

- videos.html
Couldn't find where the entry in the "docs" navigation bar pulldown is created - I hope that's done automagically :-)
> Update and rename video.html to videos.html

- docs/Reporting.md
resolve https://github.com/Codeception/codeception.github.com/issues/855
> Update Allure link

- docs/Introduction.md
Page: https://codeception.com/docs/Introduction
> Update Introduction.md: Some rewordings

- docs/AdvancedUsage.md
= https://github.com/Codeception/codeception.github.com/pull/868 without conflicts
> Update AdvancedUsage.md: Typos

- quickstart.html
The number 5 was used twice while item 4 did not exist before:
3. Create Test
5. Write a Basic Test
5. Configure Acceptance Tests
Now:
3. Create Test
4. Write a Basic Test
5. Configure Acceptance Tests
> fix numbering of headlines

- docs/modules/WebDriver.md
https://github.com/Codeception/codeception.github.com/pull/875
> fix links 

- RoboFile.php
Page: https://codeception.com/extensions
> Update RoboFile.php: Fix links to extensions' sourcecode

- _layouts/bootstrap.html
resolve https://github.com/Codeception/codeception.github.com/issues/881
> fix video url in header menu

- _layouts/bootstrap.html
resolve https://github.com/Codeception/codeception.github.com/issues/889
> update Community dropdown
