Codeception/codeception.github.com

- doc.markdown
Fixes broken links on main Doc page for Modules, Unit Tests, Advanced Usage, and Customization.  Added appropriate descriptions for Advanced Usage and Customization.
Took urls from Guides menu dropdown to relevant pages.
> Fixes broken links on Doc page and relevant explanations

- docs/02-GettingStarted.md
The link points to 06-UnitTests when it should point to 05-UnitTests.
> Fix broken link in Getting Started section

- install.html
- quickstart.html
PHP 5.4 build is recommended for PHP 5.5 too, because the main build will include PHPUnit 5 which requires PHP 5.6
> PHP 5.4 build is recommended for PHP 5.5 too

- _layouts/bootstrap.html
- _layouts/doc.html
- _layouts/index.html
- _layouts/page.html
- _layouts/post.html
- css/codeception.css
- install.html
- quickstart.html
- thanks.html
- thanks_php54.html
Removed the container from around bootstrap.html  'content'...
<div class="container"> {{ content }} </div>
...and put it around the inner layouts. This allows the use of container-fluid, eg. to fix the hero unit on the main page. Simplifies the CSS file as well.
Clicked through all the pages I could find, didn't find any broken layouts from this change.
> Correcting Bootstrap container usage.

- addons.markdown
As discussed on Codeception/Codeception#1634.
Adding brief description of Red Matter's MultiDb module which is available on packagist.org as `redmatter/codeception-multidb`.
> Mentioning MultiDb in addons.markdown

- _layouts/bootstrap.html
Instead of sending to the Codeception Category of PHPTest.club I would suggest to send this link to the latest updates, regardless if they are from Codeception category or from others like "Selenium" category.
I'm suggesting the change because I created this topic http://phptest.club/t/firefox-47-and-new-driver-marionette/916/1 that is interesting for Codeception users however is not visible in the link where Codeception.com sends you because is not in "codeception" category but under "selenium category. With the new link the person using the link at codeception.com will get to the latest messages page.
> Alternative link for PHPTest.club

- addons.markdown
I've created a tiny module which expose params from Codeception config to test scenarios and offer it to be added to Codeception's addons list.
> Add Config module to addons list

- for/wordpress.md
Due to a conflict between the version of `symfony/console` the `wp-cli/wp-cli` package requires installing `codeception/codeception` before `lucatume/wp-browser` will fail; simply requiring `lucatume/wp-browser` will fix this while still pulling `codeception/codeception` latest version.
> Remove Codeception explicit installation

- for/yii.md
We've used `composer exec` for some time but switched from it because of issues and because its purpose is slightly different. I've updated Yii guides but forgot to update the page at Codeception website.
> Switched from using composer exec to directly running commands from vendor

- thanks_php5.html
- thanks_php54.html
I updated manual download links in thanks pages to match links used in Refresh header.
Please squash commits when merging.
Closes https://github.com/Codeception/Codeception/issues/4443
> Fix phar download links

- _data/extensions.yml
- _data/modules.yml
Hello,
Since Codeception 2.5.0 (Sept 2018) multi database is in the code of codeception.
We don't need anymore a module or extension to manage more than one database.
So I think we should remove the module and extension in the documentation. And this module https://github.com/iamdevice/codeception-multidb is not updated since 1 year.
> Remove multidb module and extension in the doc

- docs/08-Customization.md
Following a [discussion on Slack](https://codeception.slack.com/archives/C93B93AUT/p1556812096004700)
- Remove extra `yml`
- Add `steps:` to make the example more explicit.
> Update config for Step decorators

- _layouts/bootstrap.html
Since Codeception's default branch is not ```master``` but ```2.5```, make the license point to it instead of pointing to a 404 error page.
> Fix Codeception license URL

- docs/07-AdvancedUsage.md
Not only strings of JSON notation!
> All strings in @example must be enclosed in double quotes

- for/wordpress.md
In some cases, the Vendor binaries are not always executable globally.
> Updated path to /vendor/bin executables

- RoboFile.php
All .tpl.dist files were renamed to .tpl in PHPUnit 8.3.0
https://github.com/sebastianbergmann/phpunit/commit/28b0458b9e9e5337fccc52a2a2c5fa46b0aa5102
> Add tpl files to phar

- docs/02-GettingStarted.md
Other places in this page mention the name `signInSuccessfully`, only this definition use `loginSuccessfully`.
> Fix inconsistent name

- 404.html
- css/codeception.css
issue https://github.com/Codeception/codeception.github.com/issues/312
> 404 page ui update

- docs/09-Data.md
Documentation for https://github.com/Codeception/Codeception/pull/5945
> Add extra snapshot file format documentation

- docs/07-AdvancedUsage.md
* "Get Scenario Metadata" probably isn't perfect, but at least conveys more meaning than "Current Values"
* This has nothing to do with environments, so I upgraded the header level
* Shuffle has nothing to do with environments, so I upgraded the header level too
* Dependencies is only useful when shuffling (right?) so I made it a sub-heading of that
I didn't change anything *inside* those chapters.
TODO: I'll add a link from WebDriver module to "Get Scenario Metadata" (as a result of our discussion at https://github.com/Codeception/Codeception/issues/6035), but only after this is merged and online, cause I need the anchor name.
> Reorganizing some headers

- _layouts/page.html
phptest.club server has not been available for a long time, so we should not expose the link.
> Disable link to forum

- docs/04-FunctionalTests.md
Fixes https://github.com/Codeception/Codeception/pull/5237
The page [Functional Tests](https://codeception.com/docs/04-FunctionalTests#Error-Reporting) mentions
> error_level can also be set globally in codeception.yml file.
but it does not mention that it needs to be under `settings` otherwise it would not work
> Update Functional Tests page

- docs/10-APITesting.md
After working through [the REST API testing documentation](https://codeception.com/docs/10-APITesting) and attempting to run the API tests, I encountered the following error:
```console
Module REST is not installed.
Use Composer to install corresponding package:
composer require codeception/module-rest --dev
```
This change updates the REST section of the API documentation to cover this requirement, so that it's not discovered when running the API tests.
> Add note that Rest API testing requires the module-rest package

- _includes/for.html
See https://github.com/Codeception/module-symfony/pull/98#issuecomment-800446510
As long as the dropdown menu does exist, I think it's better to keep Symfony in there, in order to not give the impression that Symfony isn't supported :-)
Ultimately, the dropdown should be deleted completely (or renamed to "CMS") - see https://github.com/Codeception/module-symfony/pull/98#issue-553062458
> Linking to Symfony Module

- docs/07-AdvancedUsage.md
This is missing from the code snippet. Lost more time than I'm willing to admit getting this working.
Past reference has this key in the snippet: https://github.com/Codeception/base/blame/3.1/docs/07-AdvancedUsage.md#L357
> Fix YAML for environment configuration

- docs/06-ModulesAndHelpers.md
... see https://github.com/Codeception/Codeception/issues/5359#issuecomment-754763605
Question: Which other things (like `depends`) cannot be changed?
> Adding runtime limitation

- _data/modules.yml
...since nobody is going to install these nowadays. If you want to keep them somewhere, I suggest a new heading "Legacy Modules" (or so).
I also reworded "Date/Time" a little.
> Removing Symfony1 and Doctrine1

- docs/reference/Configuration.md
Documents https://github.com/Codeception/Codeception/pull/6469
> Document convert_deprecations_to_exceptions setting

- _includes/phar.html
href attributes are required for opening/closing tabs.
Second tab must be closed by default
See https://codeception.com/install
> Fix phar download accordion

- docs/APITesting.md
The `sendPatch` method was mentioned twice in the list of common `send*` methods in ApiTesting.md. This PR removes the duplicated entry.
> Fix duplicate sendPatch reference in ApiTesting.md

- _layouts/bootstrap.html
I think this is way too prominent.
The page mainly is an overview of what GitHub gives you anyway - so does anybody really need this at all?
* If yes, I'll find another place
* If no, let's delete the page too! :-)
Same question for https://codeception.com/builds which is linked from the releases page.
> Removing "Releases" from navigation bar

- docs/Codecoverage.md
- docs/reference/Commands.md
caused by: https://github.com/Codeception/Codeception/issues/6760
caused by: https://github.com/Codeception/Codeception/pull/6761
Add some new option `--disable-coverage-php` this will not provoke BC changes
```bash
php bin/codecept run unit --coverage --coverage-html --disable-coverage-php
```
> Added documentation for the new option --disable-coverage-php

- docs/Customization.md
Found broken links in Customization page. Updated to fix + point at release 5.0
> Fixed broken links in Customization page

- _includes/extensions.md
And some minor language improvements.
> Update extensions.md: Fixing links to sourcecodes

- docs/modules/WebDriver.md
`https://sites.google.com/a/chromium.org/chromedriver/capabilities` link is dead.
> Fix ChromeDriver links

- docs/AdvancedUsage.md
References https://github.com/Codeception/Codeception/issues/6646
> Add "Examples" attribute example for associative keys
